import type { Clock, IdGenerator, StrategyGenome, Tenant } from '@wedding-planner/shared'

import { GuestAuthorizer } from '../auth/guest_authorizer'
import { OperatorCredentialStore } from '../auth/operator_credential'
import { ProviderWebhookCredentialStore } from '../auth/provider_webhook_credential'
import { SessionStore } from '../auth/session_store'
import { WeddingAuthorizer } from '../auth/wedding_authorizer'
import { BillingLedger } from '../billing/billing_ledger'
import { ProductApi } from '../http/product_api'
import { EscalationLog } from '../messaging/escalation_log'
import { EscalationResolutionLog } from '../messaging/escalation_resolution_log'
import { DeterministicGuestQaResponder } from '../messaging/guest_qa_responder'
import { GuestRegistry } from '../messaging/guest_registry'
import { InboundReceiptLog } from '../messaging/inbound_receipt_log'
import { MessagingService } from '../messaging/messaging_service'
import { SimulatedMessagingAdapter } from '../messaging/simulated_messaging_adapter'
import { OnboardingService } from '../onboarding/onboarding_service'
import { TenantContextResolver } from '../tenant/tenant_context'
import { TenantStore } from '../tenant/tenant_store'
import { ProductWebUi } from '../web/product_web_ui'
import { ThemeResolver } from '../web/theme_resolver'
import { WeddingRepository } from '../wedding/wedding_repository'

/**
 * @canonical compose_product_surface -- the composition root: wires every product-surface dependency into
 * one running web front door, with no ambient reads of its own.
 *
 * This is the seam between the deployable entrypoint (`app/server.ts`, the impure shell that reads env, the
 * wall clock, and the socket) and the pure product surface. `compose` takes its `Clock`, `IdGenerator`, and
 * the operator credential token as CONFIG — it constructs none of them, reads no env, generates no token, and
 * logs nothing. So the entrypoint injects the live edge primitives (SystemClock / RandomIdGenerator / a
 * crypto-random operator token) while tests inject the deterministic doubles (ManualClock /
 * SequentialIdGenerator / a fixed token), and both exercise the SAME wiring.
 *
 * The dependency graph it assembles is exactly the one the keystone tests build by hand: a single
 * `TenantStore` is the shared backbone (the resolver, theme resolver, onboarding driver, and wedding repo all
 * read its liveness/slug index), `ProductApi` is the 5-stage pipeline over it, and `ProductWebUi` is the
 * themed HTML front door whose ONLY data path is `api.handle()`. Nothing here widens a boundary: the three
 * token namespaces, the disclosure mask, and tenant isolation are all inherited unchanged from the pieces.
 *
 * The demo seed (when `seedDemo`) is the launch-ready touch: it provisions and activates one tenant THROUGH
 * the real `OnboardingService` lifecycle driver — provision → activate — so the demo tenant traverses the
 * legal-transition guard and records real billing events, making it indistinguishable at the edge from any
 * operator-provisioned tenant (an ACTIVE tenant disclosing existence is the designed behavior; absent /
 * suspended / onboarding stay the byte-identical 404). It then seeds one wedding via
 * `WeddingRepository.create` against a resolver-minted context obtained AFTER activation. It deliberately
 * mints NO session — the first planner logs in via the public `/t/:slug/login` edge once the image is up, so
 * no session token is baked into boot state.
 *
 * related: system_clock.ts / random_id_generator.ts (the edge primitives the entrypoint injects),
 * onboarding_service.ts (the lifecycle driver the demo seed uses), product_web_ui.ts (the returned front door).
 */

/** Config for {@link composeProductSurface}. The clock/ids/token are INJECTED — compose reads no ambient state. */
export interface ComposeProductSurfaceConfig {
  /** Time source. Inject `ManualClock` in tests; the entrypoint injects the edge `SystemClock`. */
  readonly clock: Clock
  /** Identity source. Inject `SequentialIdGenerator` in tests; the entrypoint injects `RandomIdGenerator`. */
  readonly ids: IdGenerator
  /** The single platform-operator credential token (already validated/generated by the caller). */
  readonly operatorToken: string
  /**
   * Phase 19: the provider-webhook secret authenticating the inbound messaging webhook (the FOURTH token
   * namespace). Injected like the operator token — compose generates none and reads no env. The entrypoint
   * supplies a validated/generated secret; tests inject a fixed one.
   */
  readonly providerWebhookToken: string
  /** Seed + activate a demo tenant so the image boots demoable. Default true. */
  readonly seedDemo?: boolean
  /** The demo tenant's slug (the public routing key). Default 'demo'. */
  readonly demoSlug?: string
  /**
   * Phase 17: the loop's champion strategy genome, surfaced read-only to planners (the engine↔surface seam).
   * Injected as a `@wedding-planner/shared` VALUE — compose imports no loop/eval code, so the acyclic-workspace
   * and determinism rails hold. Forwarded verbatim to `ProductApi`, which projects + validates it (an invalid
   * champion throws here, aborting boot). Absent ⇒ the `/t/:slug/strategy` route 404s.
   */
  readonly championStrategy?: StrategyGenome
}

/** A handle to the seeded demo tenant — present only when `seedDemo` was true. */
export interface DemoSeed {
  readonly slug: string
  readonly tenantId: string
  readonly weddingId: string
  /** Phase 19: the demo guest's opaque sender ref, registered to the demo wedding (drives the inbound demo). */
  readonly guestRecipientRef: string
}

/** The wired product surface. `ui` is the deployable front door; the rest are exposed for tests/inspection. */
export interface ComposedSurface {
  readonly ui: ProductWebUi
  readonly api: ProductApi
  readonly themes: ThemeResolver
  /** Echoed back so the entrypoint can log provenance (NEVER an env-provided token — caller's concern). */
  readonly operatorToken: string
  /** The demo tenant handle, or undefined when `seedDemo` was false (no fabricated handle). */
  readonly demo?: DemoSeed
  /**
   * Phase 18: the metered, margin-priced guest-messaging service, wired over the offline simulated provider
   * adapter (which takes the SAME injected clock/ids, so the determinism rail holds). Exposed for
   * tests/inspection — it has no HTTP route yet (the guest-channel request edge is the next rung), so this is
   * how a compose-level test exercises `send` through the wired graph.
   */
  readonly messaging: MessagingService
  /**
   * Phase 26: the escalation inbox — the log of guest questions the platform could not answer. Exposed for
   * tests/inspection (read over HTTP via `GET /t/:slug/escalations`); a compose-level e2e uses it to verify
   * the guest->couple loop (an escalated question lands here, then a filled fact makes the next ask answerable).
   */
  readonly escalations: EscalationLog
  /**
   * Phase 27: the append-only escalation-resolution log (resolved/dismissed). Exposed for tests/inspection
   * (read/written over HTTP via `GET`/`POST /t/:slug/escalations`); a compose-level e2e uses it to verify the
   * couple can mark an escalated question handled (it moves out of the Open inbox) idempotently.
   */
  readonly resolutions: EscalationResolutionLog
}

/** The demo theme — an obvious offline placeholder (no real brand). Colors are lowercase 6-hex per contract. */
const DEMO_THEME: Tenant['theme'] = {
  brand_name: 'Demo Weddings Co.',
  primary_color_hex: '#3b5bdb',
  accent_color_hex: '#f06595',
  logo_ref: 'demo_logo',
}

/** Build the fully-wired product surface from injected primitives. Performs no ambient reads. */
export function composeProductSurface(config: ComposeProductSurfaceConfig): ComposedSurface {
  const { clock, ids, operatorToken } = config
  const seedDemo = config.seedDemo ?? true
  const demoSlug = config.demoSlug ?? 'demo'

  // The shared backbone: one tenant store the resolver, theme resolver, onboarding, and repo all read.
  const tenants = new TenantStore(clock, ids)
  const resolver = new TenantContextResolver(tenants)
  const sessionStore = new SessionStore(ids)
  const operators = new OperatorCredentialStore(ids, [operatorToken])
  const webhookCredentials = new ProviderWebhookCredentialStore(ids, [config.providerWebhookToken])
  const billing = new BillingLedger(clock, ids)
  const onboarding = new OnboardingService(tenants, billing)
  const weddings = new WeddingRepository(tenants, clock, ids)
  const authorizer = new WeddingAuthorizer()

  // The guest-messaging provider boundary (Phase 18): the offline simulated adapter is a deterministic
  // double (injected clock/ids — no real provider, no network), so it wires here like any dep without
  // breaching the determinism rail. The service meters accepted sends and bills usage_charge into the SAME
  // ledger. No HTTP route yet (the guest-channel edge is the next rung); exposed on the surface for tests.
  const messagingAdapter = new SimulatedMessagingAdapter(clock, ids)
  const messaging = new MessagingService(messagingAdapter, tenants, billing, ids)

  // The guest inbound channel (Phase 19): a guest texts in over the provider webhook and the deterministic
  // responder answers from the bound wedding, metered through the service. The registry + receipt log inherit
  // tenant isolation (they read the same TenantStore liveness); the responder is pure. No loop import.
  const guestRegistry = new GuestRegistry(tenants)
  const guestAuthorizer = new GuestAuthorizer()
  const inboundReceipts = new InboundReceiptLog(tenants, ids)
  const guestResponder = new DeterministicGuestQaResponder()
  // The escalation inbox (Phase 26): an `escalated` question is recorded here and read by the couple (their
  // wedding) / planner (whole tenant). ONE instance — the inbound capture writes it, the read surface reads it.
  const escalations = new EscalationLog(tenants, ids)
  // The escalation-resolution log (Phase 27): the append-only handled-record (resolved/dismissed) keyed by
  // escalation_id, scoped exactly like the escalations. ONE instance — the resolve mutation writes it, the read
  // surface returns it alongside the escalations. Stamps resolved_at from the same injected clock.
  const resolutions = new EscalationResolutionLog(tenants, ids, clock)

  const api = new ProductApi({
    resolver,
    sessionStore,
    weddings,
    authorizer,
    guests: { registry: guestRegistry, weddings, authorizer: guestAuthorizer },
    operators,
    onboarding,
    webhookCredentials,
    messaging: {
      port: messagingAdapter,
      receipts: inboundReceipts,
      registry: guestRegistry,
      weddings,
      responder: guestResponder,
      service: messaging,
      escalations,
    },
    // The escalation inbox READ + RESOLVE + REPLY surface (Phase 26 + 27 + 28) — the SAME log instances the
    // inbound capture / resolve / reply mutations write to, read-scoped by the guest authorizer's manageScope
    // (planner: whole tenant; couple: their wedding). `service` is the SAME MessagingService the inbound path
    // uses, so a console reply and a guest reply meter/bill through ONE ledger (Phase 28).
    escalations: { escalations, resolutions, authorizer: guestAuthorizer, service: messaging },
    // The planner billing & usage summary (Phase 30): the ledger NARROWED to its read fold (`summarize`), the
    // tenant store narrowed to `findById` (the trusted plan_tier of the caller's own tenant), and the
    // management-capability authorizer for the planner-only gate. Always wired (a compose e2e pins reachability).
    billing: { ledger: billing, tenants, authorizer: guestAuthorizer },
    ...(config.championStrategy === undefined ? {} : { championStrategy: config.championStrategy }),
  })
  const themes = new ThemeResolver(tenants)
  // The web UI gets the SessionStore typed as the narrow CsrfGuard (issue/verify only — not login/resolve),
  // so it can check anti-forgery tokens but reads no tenant data (the only-data-path-is-api.handle invariant).
  const ui = new ProductWebUi({ api, themes, csrf: sessionStore })

  let demo: DemoSeed | undefined
  if (seedDemo) {
    // Provision → activate THROUGH the real lifecycle driver (not a direct store.create), so the demo
    // tenant is a faithful active tenant: it passes the legal-transition guard and records billing events.
    const tenant = onboarding.provision({
      slug: demoSlug,
      display_name: 'Demo Weddings Co.',
      plan_tier: 'studio',
      theme: DEMO_THEME,
    })
    onboarding.activate(tenant.tenant_id)
    // The tenant is now active, so the resolver mints a usable context — seed one wedding through it.
    const context = resolver.resolveBySlug(demoSlug)
    const wedding = weddings.create(context, {
      couple_display_name: 'Alex & Sam',
      event_date: '2027-09-18',
    })
    // Register one demo guest so the inbound webhook -> deterministic reply -> meter path is demoable
    // end-to-end. The recipient_ref is an obvious offline placeholder (no real number).
    const guestRecipientRef = 'sms:+15550100'
    guestRegistry.register(context, {
      recipient_ref: guestRecipientRef,
      wedding_id: wedding.wedding_id,
      guest_id: 'guest_demo_1',
    })
    demo = {
      slug: demoSlug,
      tenantId: tenant.tenant_id,
      weddingId: wedding.wedding_id,
      guestRecipientRef,
    }
  }

  return { ui, api, themes, operatorToken, demo, messaging, escalations, resolutions }
}
